
scala:
  - 2.11.12
  - 2.12.11
  - 2.13.2

language: scala
script: >
  sbt ++$TRAVIS_SCALA_VERSION check coverage sql_formatterJVM/test sql_formatterJVM/coverageReport sql_formatterJS/test

matrix:
  include:
    - scala: 2.11.12
      before_script:
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      sudo: required
      script: sbt ++$TRAVIS_SCALA_VERSION! sql_formatterNative/test

jdk:
  - openjdk8
  - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
